apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        role: worker-1  # Memaksa ke Worker Node 1
      containers:
      - name: curl-client
        image: curlimages/curl
        command: ["sh", "-c", "sleep infinity"]
